import type { Metadata } from "next";

//fonts
import { Poppins, Kaisei_Tokumin } from "next/font/google";

// styles
import "../globals.css";
import "../variables.module.css";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  variable: "--font-poppins",
});

const kaiseiTokumin = Kaisei_Tokumin({
  subsets: ["latin"],
  weight: ["700"],
  variable: "--font-kaisei",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${kaiseiTokumin.variable}`}>
        {children}
      </body>
    </html>
  );
}
